
services:


  frontend:
    build: ./frontend
    container_name: react_container
    volumes:
      - frontend-build:/app

  
  backend:
    build: ./backend
    ports:
      - 3000:3000
    container_name: express_container
    env_file:
      - ./backend/.env
    depends_on:
      - frontend
    volumes:
      - frontend-build:/app/frontend

volumes:
  frontend-build: